import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Intro from "../components/Intro"
import About from "../components/About"
import Services from '../components/Services'
import { data } from '../data'
import Testimonial from '../components/Testimonial'

export default function Home({services}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ivo Rush </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Intro/>
      <Services services={services}/>
<Testimonial/>

     
    </div>
  )
}
export const getStaticProps = async ()=>{
  const services = data;
 
  return{
    props: { services } ,
    
  }
};